import { ArrowRight, FileText, Mail, SendHorizontal, Sparkles, ChevronsUpDown, Search, Trash, Moon, Menu, RectangleEllipsis, X, Lock, Pen, Check, Eraser, VolumeX, Sun, Printer, WholeWord, Radar, Volume2, RefreshCw, Redo, Settings2, ChevronUp, Plus, Minus, ChevronRight, Shuffle, ChevronDown, ArrowUpToLine, Info, Undo, Save, Share, ChevronLeft, Pencil } from "lucide-react-native";
import { iconWithClassName } from "./iconWithClassName";

iconWithClassName(FileText);
iconWithClassName(Mail);
iconWithClassName(ArrowRight);
iconWithClassName(Sparkles);
iconWithClassName(SendHorizontal);
iconWithClassName(ChevronsUpDown);
iconWithClassName(Search);
iconWithClassName(Trash);
iconWithClassName(Moon);
iconWithClassName(Menu);
iconWithClassName(RectangleEllipsis);
iconWithClassName(X);
iconWithClassName(Lock);
iconWithClassName(Pen);
iconWithClassName(Check);
iconWithClassName(Eraser);
iconWithClassName(VolumeX);
iconWithClassName(Sun);
iconWithClassName(Printer);
iconWithClassName(WholeWord);
iconWithClassName(Radar);
iconWithClassName(Volume2);
iconWithClassName(RefreshCw);
iconWithClassName(Redo);
iconWithClassName(Settings2);
iconWithClassName(ChevronUp);
iconWithClassName(Plus);
iconWithClassName(Minus);
iconWithClassName(ChevronRight);
iconWithClassName(Shuffle);
iconWithClassName(ChevronDown);
iconWithClassName(ArrowUpToLine);
iconWithClassName(Info);
iconWithClassName(Undo);
iconWithClassName(Save);
iconWithClassName(Share);
iconWithClassName(ChevronLeft);
iconWithClassName(Pencil);

export { FileText, Mail, ArrowRight, Sparkles, SendHorizontal, ChevronsUpDown, Search, Trash, Moon, Menu, RectangleEllipsis, X, Lock, Pen, Check, Eraser, VolumeX, Sun, Printer, WholeWord, Radar, Volume2, RefreshCw, Redo, Settings2, ChevronUp, Plus, Minus, ChevronRight, Shuffle, ChevronDown, ArrowUpToLine, Info, Undo, Save, Share, ChevronLeft, Pencil };
